POST http://localhost:3000/auth/login
 Content-Type: application/json

 {
  "email": "john@gmail.com",
  "password": "12345"
 }
####
POST http://localhost:3000/auth/register
 Content-Type: application/json

 {
  "name": "Jenö Berger",
  "email": "john@gmail.com",
  "password": "1234",
 }

