//PDFs

POST http://localhost:3000/database/addPDF
Content-Type: application/json

{
  "name": "KA.pdf"
}
###
GET http://localhost:3000/database/pdf/WIRE-Organisation.pdf
###
GET http://localhost:3000/database/pdfID/2
###
DELETE http://localhost:3000/database/pdf/QM-Zusammenfassung.pdf
###
POST http://localhost:3000/database/PDFnotiz
Content-Type: application/json

{
  "title": "Database Test",
  "content": "It's Working!!!!!",
  "userID": 1,
  "pdfID": 39
}
###
GET http://localhost:3000/database/PDFnotiz/39
###
DELETE http://localhost:3000/database/note/37
###
GET http://localhost:3000/database/PDFnotiz/49
###
GET http://localhost:3000/database/PDFnote/48
###
PATCH http://localhost:3000/database/note/48
Content-Type: application/json

{
  "title": "Patch test title33",
  "content": "Patch test content"
}

// PowerPoint

###
GET http://localhost:3000/database/pptDateien
###
GET http://localhost:3000/database/pptDatei/1
###
DELETE http://localhost:3000/database/pptDatei/1
###
POST http://localhost:3000/database/pptDatei
Content-Type: application/json

{
  "src": "http://dasdassdasdasd556.ppt",
  "width": 1920,
  "height": 1080
}

// PowerPoint Notizen
###
GET http://localhost:3000/database/pptNotizen
###
POST http://localhost:3000/database/pptNotiz
Content-Type: application/json

{
  "title": "Die Zweite Testnotiz für PowerPoint.",
  "content": "Das ist ein Inhalt von einer PowerPoint-Notiz",
  "userID": 1,
  "pptID": 2
}

// YouTube
###
GET http://localhost:3000/database/video/27
###
GET http://localhost:3000/database/ytNotes/21
###
POST http://localhost:3000/database/ytNote
Content-Type: application/json

{
  "title": "Coole stelle im video",
  "content": "Hier wurde einiges gemacht.",
  "userID": 1,
  "videoID": 29,
  "time": "00:15:00"
}
###
GET http://localhost:3000/database/ytNote/9
###
DELETE http://localhost:3000/database/ytNote/10
###
PATCH http://localhost:3000/database/ytNote/9
Content-Type: application/json

{
  "title": "Testnotiz bearbeitet",
  "content": "Erfolgreich bearbeitet hehe"
}